apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops-service
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30007